### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by AndrWeisR** [cmdr2/stable-diffusion-ui#11]
First time run of this... I have a laptop Nvidia 3060 GPU, running Ubuntu in WSL on Windows 10. I tried my first prompt from the web page but got this error below. I didn't install the Nvidia driver within Ubuntu because a) it didn't recognise my GPU and b) I had all sorts of other problems. Do I need to install the Nvidia driver within WSL, or does it use the host driver?

```
sd     | ERROR:    Exception in ASGI application
sd     | Traceback (most recent call last):
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
sd     |     result = await app(self.scope, self.receive, self.send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
sd     |     return await self.app(scope, receive, send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
sd     |     await super().__call__(scope, receive, send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
sd     |     await self.middleware_stack(scope, receive, send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
sd     |     raise exc
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
sd     |     await self.app(scope, receive, _send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
sd     |     raise exc
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
sd     |     await self.app(scope, receive, sender)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
sd     |     raise e
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
sd     |     await self.app(scope, receive, send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
sd     |     await route.handle(scope, receive, send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
sd     |     await self.app(scope, receive, send)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
sd     |     response = await func(request)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
sd-ui  | INFO:     172.18.0.1:59682 - "POST /image HTTP/1.1" 500 Internal Server Error
sd     |     raw_response = await run_endpoint_function(
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
sd     |     return await run_in_threadpool(dependant.call, **values)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
sd     |     return await anyio.to_thread.run_sync(func, *args)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
sd     |     return await get_asynclib().run_sync_in_worker_thread(
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
sd     |     return await future
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
sd     |     result = context.run(func, *args)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/http.py", line 79, in predict
sd     |     output = predictor.predict(**request.input.dict())
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
sd     |     return func(*args, **kwargs)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
sd     |     return func(*args, **kwargs)
sd     |   File "/src/predict.py", line 88, in predict
sd     |     output = self.pipe(
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
sd     |     return func(*args, **kwargs)
sd     |   File "/src/image_to_image.py", line 156, in __call__
sd     |     noise_pred = self.unet(
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
sd     |     return forward_call(*input, **kwargs)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 168, in forward
sd     |     sample = upsample_block(
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
sd     |     return forward_call(*input, **kwargs)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/diffusers/models/unet_blocks.py", line 1037, in forward
sd     |     hidden_states = attn(hidden_states, context=encoder_hidden_states)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
sd     |     return forward_call(*input, **kwargs)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/diffusers/models/attention.py", line 168, in forward
sd     |     x = block(x, context=context)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
sd     |     return forward_call(*input, **kwargs)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/diffusers/models/attention.py", line 196, in forward
sd     |     x = self.attn1(self.norm1(x)) + x
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
sd     |     return forward_call(*input, **kwargs)
sd     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/diffusers/models/attention.py", line 254, in forward
sd     |     attn = sim.softmax(dim=-1)
sd     | RuntimeError: CUDA error: unknown error
sd     | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
sd     | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by cmdr2** [comment]
Hi,

AFAIK it'll use the host driver. Have you updated your NVIDIA driver to the latest version?

And can you please check if you've installed [nvidia-container-toolkit](https://stackoverflow.com/a/58432877) inside your WSL?

Thanks

**Comment by cmdr2** [comment]
Also, are you able to run the `nvidia-smi` command within your WSL? If so, can you please check if it has CUDA version > 11.6, and that it shows your GPU? Thanks

**Comment by AndrWeisR** [comment]
This is what nvidia-smi shows:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 512.15       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    22W /  N/A |      0MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by cmdr2** [comment]
Thanks. Do you have [nvidia-container-toolkit](https://stackoverflow.com/a/58432877) installed inside your WSL?

**Comment by AndrWeisR** [comment]
I updated to the latest Nvidia driver, and now I have CUDA 11.7, but the error remains.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0    23W /  N/A |      0MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by AndrWeisR** [comment]
> Thanks. Do you have [nvidia-container-toolkit](https://stackoverflow.com/a/58432877) installed inside your WSL?

Yes, I set it up as per the official install instructions, and tested it with `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi` and it gave the same nvidia-smi output as above, so I assume it's installed correctly.

**Comment by AndrWeisR** [comment]
I wonder if this has something to do with it:

```
hwinfo --gfxcard --short
graphics card:
                       Microsoft 3D controller
                       Microsoft 3D controller

Primary display adapter: #6
```

WSL doesn't seem to be detecting my nvidia card, but the integrated Intel gfx.

**Comment by cmdr2** [comment]
Hmm, yeah that is odd. Can you check if your WSL kernel is updated? Just came across this https://github.com/microsoft/wslg/issues/86#issuecomment-829563208

Also, can you please run `docker exec -it sd nvidia-smi` (assuming that you've started this project already)? That should tell us whether this project's docker container thinks it has the right GPU.

**Comment by AndrWeisR** [comment]
> docker exec -it sd nvidia-smi

Looks OK I guess?

```
sudo docker exec -it sd nvidia-smi
Fri Aug 26 14:35:23 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P0    23W /  N/A |   3251MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A         1      C   /python3.10                     N/A      |
+-----------------------------------------------------------------------------+
```

**Comment by AndrWeisR** [comment]
A ha! I updated the WSL kernel to latest and now it works!
