### ISSUE TITLE
stability-ai: could not select device driver "" with capabilities [[gpu]]

### ISSUE THREAD

**Issue by WolfShadowheart** [cmdr2/stable-diffusion-ui#27]
root@wolf-run:/home/wolf/Downloads/stable-diffusion-ui# sudo docker-compose up &
[1] 6146
Starting sd ... error

ERROR: for sd  Cannot start service stability-ai: could not select device driver "" with capabilities: [[gpu]]

ERROR: for stability-ai  Cannot start service stability-ai: could not select device driver "" with capabilities: [[gpu]]
ERROR: Encountered errors while bringing up the project.

Apologies if this is simply the GPU issue, however I did try to follow that only for this to persist. Thanks!

**Comment by HVRyan** [comment]
First, make sure you have an nVidia GPU -- right now, it's the minimum requirement. From there, you want 10GB. It can be done on 6GB or even 4GB, but needs an optimized model to do so.

Check that you have all the needed nvidia drivers installed. 

nvidia-driver-515 and nvidia-cuda-toolkit should be the core packages, you might need to install nvidia-container-toolkit if either of the other two doesn't include it.

After install, you want to reboot to ensure they loaded properly

**Comment by GregHilston** [comment]
@WolfShadowheart I resolved this by running

```
sudo apt-get update -y
sudo apt-get install -y nvidia-container-toolkit
sudo systemctl restart docker
```

Which I learned about from [here](https://github.com/NVIDIA/nvidia-docker/issues/1243)

Hope that helps!

**Comment by WolfShadowheart** [comment]
Thank both of you, I will give this another shot!

**Comment by cmdr2** [comment]
Yes, `nvidia-container-toolkit` needs to be installed for this to run.

If this fails, please try the v2 beta version from https://github.com/cmdr2/stable-diffusion-ui/tree/v2#system-requirements (which doesn't require docker or WSL or nvidia-container-toolkit). Thanks
