### ISSUE TITLE
Error: Unexpected Read Error:

### ISSUE THREAD

**Issue by The-QCC** [cmdr2/stable-diffusion-ui#774]
Loading any image as N INITIAL IMAGE.. After the error, no other image may be generated.
The only recourse is to reboot the computer.
Error:undefined
EventInfo: {
    "reader": {}
}
Error: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.*
HP Z640, Nvidia Geforce 980Ti
Windows 10 Pro
Firefox 108.0.2 (64-bit)
![D_initial_image_error](https://user-images.githubusercontent.com/122744905/212558151-cac7d4a5-869a-4047-8574-f1471fb3dff8.png)

 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
Duplicate of #741

Your prompt strength is very small which triggers a bug in the stable diffusion engine.

**Comment by The-QCC** [comment]
Interesting.
I made a new install on another drive from the ZIP file stable-diffusion-ui-windows downloaded at 9:39PM. The previous install was called Easy Diffusion. The last install is Stable Diffusion UI v2.4.24.
I was going to write "Where is the prompt strength setting?"
Apparently it only shows if an initial image is used..
So problem solved.
Thank you

**Comment by JeLuF** [comment]
v2.4.24 is the stable version.
v2.5.6 is the current development version, called "beta".

**Comment by JeLuF** [comment]
This seems to be fixed as of 2.5.12(beta)
